---
language: ruby
script:
  - "bundle exec rake validate lint spec SPEC_OPTS='--format documentation'"
sudo: false
matrix:
  include:
  # Debian 7
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7.23" FACTER_GEM_VERSION="~> 1.6.10"
  # Debian 8 with strict variables
  - rvm: 2.1.5
    env: STRICT_VARIABLES="yes" PUPPET_GEM_VERSION="~> 3.7.2" FACTER_GEM_VERSION="~> 2.2.0"
  # Debian 9 with strict variables
  - rvm: 2.3.3
    env: STRICT_VARIABLES="yes" PUPPET_GEM_VERSION="~> 4.8.2" FACTER_GEM_VERSION="~> 2.4.6"

notifications:
  email:
    - al@lab42.it
