name 'example42-apt'
version '2.0.7'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-apt'
summary 'Puppet module for apt'
description 'This module manages apt'
dependency 'example42/puppi', '>= 2.0.0'
